import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header, Menu } from "@/components";
import { Footer } from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster";
import Providers from "@/app/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "SmartStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Menu />
        <Toaster />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
