import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header, Menu } from "@/components";
<<<<<<< HEAD
import { Footer } from "@/components/footer/Footer";
=======
import { Toaster } from "@/components/ui/toaster"
>>>>>>> 4549eb0109f3b81a28c6f7fbb8128c38d5be018c

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <Menu />
        {children}
<<<<<<< HEAD
        <Footer />
=======
        <Toaster />
>>>>>>> 4549eb0109f3b81a28c6f7fbb8128c38d5be018c
      </body>
    </html>
  );
}
