import {Product} from "@/lib/types/productInterface"

export const productList: Product[] = [
  {
    id: 1,
    photoUrl: "/images/alienware.jpg",
    name: "Auriculares Bluetooth",
    brand: "Alienware",
    description:
      "Auriculares inalámbricos con excelente calidProductoad de sonidProductoo.",
    price: 50,
    category: "Auriculares",
    stock: 20,
    shortDescription: "",
    sellerId: 0,
  },
  {
    id: 2,
    photoUrl: "/images/xiaomi.jpg",
    name: "Smartphone",
    brand: "Xiaomi",
    description: "Smartphone con pantalla OLED y cámara de alta resolución.",
    price: 800,
    category: "Smartphones",
    stock: 20,
    shortDescription: "",
    sellerId: 1,
  },
  {
    id: 3,
    photoUrl: "/images/alienware.jpg",
    name: "Laptop Gamer",
    brand: "Dell",
    description:
      "Laptop con procesador potente y tarjeta gráfica de última generación.",
    price: 1200,
    category: "Laptops",
    stock: 20,
    shortDescription: "",
    sellerId: 1,
  },
  {
    id: 4,
    photoUrl: "/images/xiaomi.jpg",
    name: "Mouse Inalámbrico",
    brand: "Logitech",
    description: "Mouse inalámbrico ergonómico con gran precisión.",
    price: 25,
    category: "Mouse",
    stock: 20,
    shortDescription: "",
    sellerId: 1,
  },
  {
    id: 5,
    photoUrl: "/images/alienware.jpg",
    name: "Smartwatch",
    brand: "Samsung",
    description: "Reloj inteligente con monitoreo de salud y notificaciones.",
    price: 150,
    category: "SmartWatch",
    stock: 20,
    shortDescription: "",
    sellerId: 1,
  },
  {
    id: 6,
    photoUrl: "/images/xiaomi.jpg",
    name: "Teclado Mecánico",
    brand: "MSI",
    description: "Teclado mecánico RGB con switches personalizables.",
    price: 100,
    category: "Teclados",
    stock: 20,
    shortDescription: "",
    sellerId: 1,
  },
];
